import z from "zod";

const assetDescriptionSchema = z.object({
    "appid": z.number(),
    "classid": z.string(),
    "instanceid": z.string(),
    "background_color": z.string(),
    "icon_url": z.string(),
    "tradable": z.number(),
    "name": z.string(),
    "name_color": z.string(),
    "type": z.string(),
    "market_name": z.string(),
    "market_hash_name": z.string(),
    "commodity": z.number()
})

const itemSchema = z.object({
    name: z.string(),
    hash_name: z.string(),
    sell_listings: z.number(),
    sell_price: z.number(),
    sell_price_text: z.string(),
    app_icon: z.string(),
    app_name: z.string(),
    asset_description: assetDescriptionSchema,
    sale_price_text: z.string(),
})

export const responseSchema = z.object({
    success: z.boolean(),
    start: z.number(),
    pagesize: z.number(),
    total_count: z.number(),
    searchdata: z.object({
        query: z.string(),
        search_descriptions: z.boolean(),
        total_count: z.number(),
        pagesize: z.number(),
        prefix: z.string(),
        class_prefix: z.string(),
    }),
    results: z.array(itemSchema)
})

export type MarketResponse = z.infer<typeof responseSchema>

export const defaultMarketResponse: MarketResponse = {
    "success": true,
    "start": 0,
    "pagesize": 20,
    "total_count": 17,
    "searchdata": {
        "query": "",
        "search_descriptions": false,
        "total_count": 17,
        "pagesize": 20,
        "prefix": "searchResults",
        "class_prefix": "market"
    },
    "results": [
        {
            "name": "Sticker Capsule 2",
            "hash_name": "Sticker Capsule 2",
            "sell_listings": 1274,
            "sell_price": 1498,
            "sell_price_text": "$14.98",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "384801279",
                "instanceid": "302028390",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bjn_lDkShjjoYbh_ikLvbz6Mac1c_SWCjaUk7tytblqTH3rwxki527Sw9j7c32XbQAhWMYlE7ENrFDmxQkjC0Ti",
                "tradable": 1,
                "name": "Sticker Capsule 2",
                "name_color": "D2D2D2",
                "type": "Bedna (Základní třída)",
                "market_name": "Sticker Capsule 2",
                "market_hash_name": "Sticker Capsule 2",
                "commodity": 1
            },
            "sale_price_text": "$14.33"
        },
        {
            "name": "Samolepka | Let's Roll-oll",
            "hash_name": "Sticker | Let's Roll-oll",
            "sell_listings": 246,
            "sell_price": 19,
            "sell_price_text": "$0.19",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370196511",
                "instanceid": "188530139",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsj47030fg_-kprf8i5Xoav3PvNoJaCSVjHGmeoktbUwGHnmw0ok4mSBwtmvcn-fOgMmCZR0EeAU8k7vZOsCOqc",
                "tradable": 1,
                "name": "Samolepka | Let's Roll-oll",
                "name_color": "D2D2D2",
                "type": "Samolepka (Vyšší třída)",
                "market_name": "Samolepka | Let's Roll-oll",
                "market_hash_name": "Sticker | Let's Roll-oll",
                "commodity": 1
            },
            "sale_price_text": "$0.18"
        },
        {
            "name": "Samolepka | Metal",
            "hash_name": "Sticker | Metal",
            "sell_listings": 185,
            "sell_price": 23,
            "sell_price_text": "$0.23",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370199686",
                "instanceid": "188530139",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsj5703mTVOmn5firCNZu6r8bPZvJKSXWD-Rl-sltrk8G3vqzUgl4WrQmNmpdHKRcEZ-XU9JdaNk",
                "tradable": 1,
                "name": "Samolepka | Metal",
                "name_color": "D2D2D2",
                "type": "Samolepka (Vyšší třída)",
                "market_name": "Samolepka | Metal",
                "market_hash_name": "Sticker | Metal",
                "commodity": 1
            },
            "sale_price_text": "$0.22"
        },
        {
            "name": "Samolepka | Chicken Lover",
            "hash_name": "Sticker | Chicken Lover",
            "sell_listings": 140,
            "sell_price": 43,
            "sell_price_text": "$0.43",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370203990",
                "instanceid": "188530139",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsj34lDkShj_oZrv6ydJoab4MPZpc_PBDzXDl-ggs7M4Hy-ylhhyt22Amdj8JX_FZ1UnA8QmE-YU8k7vYJs36dk",
                "tradable": 1,
                "name": "Samolepka | Chicken Lover",
                "name_color": "D2D2D2",
                "type": "Samolepka (Vyšší třída)",
                "market_name": "Samolepka | Chicken Lover",
                "market_hash_name": "Sticker | Chicken Lover",
                "commodity": 1
            },
            "sale_price_text": "$0.42"
        },
        {
            "name": "Samolepka | Good Game",
            "hash_name": "Sticker | Good Game",
            "sell_listings": 112,
            "sell_price": 490,
            "sell_price_text": "$4.90",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370196642",
                "instanceid": "188530139",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsjz5VbjRhz8m9jlrXAOtvb_PKI6cvOVCmLFle0nseM4H3DrlEkl42WHmd78dXyVbA4oFNIuEhUNvd1i",
                "tradable": 1,
                "name": "Samolepka | Good Game",
                "name_color": "D2D2D2",
                "type": "Samolepka (Vyšší třída)",
                "market_name": "Samolepka | Good Game",
                "market_hash_name": "Sticker | Good Game",
                "commodity": 1
            },
            "sale_price_text": "$4.69"
        },
        {
            "name": "Samolepka | Bomb Code",
            "hash_name": "Sticker | Bomb Code",
            "sell_listings": 99,
            "sell_price": 86,
            "sell_price_text": "$0.86",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370199479",
                "instanceid": "188530139",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsj25VTlfh7-mpOu-yQDu_asbPQ7cfOXXmPIkboh5-AxHX3lx0tw62XczdyucXnCaQQhD4wwG7B88LNKHw",
                "tradable": 1,
                "name": "Samolepka | Bomb Code",
                "name_color": "D2D2D2",
                "type": "Samolepka (Vyšší třída)",
                "market_name": "Samolepka | Bomb Code",
                "market_hash_name": "Sticker | Bomb Code",
                "commodity": 1
            },
            "sale_price_text": "$0.83"
        },
        {
            "name": "Samolepka | Banana",
            "hash_name": "Sticker | Banana",
            "sell_listings": 52,
            "sell_price": 127,
            "sell_price_text": "$1.27",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370200731",
                "instanceid": "188530139",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsj261fmTxy_ncWypXde6aL7aqJvcaiXDDGUwLYv5uNvGHC2l0l0sj-ByN2sIHrBaBhgVMXwKPP2hQ",
                "tradable": 1,
                "name": "Samolepka | Banana",
                "name_color": "D2D2D2",
                "type": "Samolepka (Vyšší třída)",
                "market_name": "Samolepka | Banana",
                "market_hash_name": "Sticker | Banana",
                "commodity": 1
            },
            "sale_price_text": "$1.22"
        },
        {
            "name": "Samolepka | Good Luck",
            "hash_name": "Sticker | Good Luck",
            "sell_listings": 51,
            "sell_price": 152,
            "sell_price_text": "$1.52",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370198576",
                "instanceid": "7437618994",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsjz5VbjTQjyldjhqXYDufH5aaFseabLD2aTw-gi5bgxSnvqwkwit2vTztasc3uUOgJ2FNIuEnevrBpg",
                "tradable": 1,
                "name": "Samolepka | Good Luck",
                "name_color": "D2D2D2",
                "type": "Samolepka (Vyšší třída)",
                "market_name": "Samolepka | Good Luck",
                "market_hash_name": "Sticker | Good Luck",
                "commodity": 1
            },
            "sale_price_text": "$1.46"
        },
        {
            "name": "Samolepka | Bash (holografická)",
            "hash_name": "Sticker | Bash (Holo)",
            "sell_listings": 42,
            "sell_price": 469,
            "sell_price_text": "$4.69",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370197980",
                "instanceid": "188530139",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsj260rvfhX-kpmuqHdf6vP5PKI1IaTGVj6Vkuhws-BoFnnnzUgltmmGyY77IyjEaFJxXowwG7CRGcYc-g",
                "tradable": 1,
                "name": "Samolepka | Bash (holografická)",
                "name_color": "D2D2D2",
                "type": "Samolepka (Významná)",
                "market_name": "Samolepka | Bash (holografická)",
                "market_hash_name": "Sticker | Bash (Holo)",
                "commodity": 1
            },
            "sale_price_text": "$4.49"
        },
        {
            "name": "Samolepka | Welcome to the Clutch",
            "hash_name": "Sticker | Welcome to the Clutch",
            "sell_listings": 41,
            "sell_price": 115,
            "sell_price_text": "$1.15",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370198464",
                "instanceid": "7454668340",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsjj71XkThD0oZXs6DZY57z6bKI5eKTFDGXDwL9wteBtFirrwEsmsTjQm96ocS3EPVAhAsB1F7QIrFDmxRUFa3Qh",
                "tradable": 1,
                "name": "Samolepka | Welcome to the Clutch",
                "name_color": "D2D2D2",
                "type": "Samolepka (Vyšší třída)",
                "market_name": "Samolepka | Welcome to the Clutch",
                "market_hash_name": "Sticker | Welcome to the Clutch",
                "commodity": 1
            },
            "sale_price_text": "$1.10"
        },
        {
            "name": "Samolepka | Bish (holografická)",
            "hash_name": "Sticker | Bish (Holo)",
            "sell_listings": 40,
            "sell_price": 566,
            "sell_price_text": "$5.66",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370201720",
                "instanceid": "188530139",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsj240rvfhX-kpmu-yBevqP2O_E4I6mVDTCWlLYjtblvG3vglEt-4m3VzdmpIimSOAImWIwwG7DEtAgJ5w",
                "tradable": 1,
                "name": "Samolepka | Bish (holografická)",
                "name_color": "D2D2D2",
                "type": "Samolepka (Významná)",
                "market_name": "Samolepka | Bish (holografická)",
                "market_hash_name": "Sticker | Bish (Holo)",
                "commodity": 1
            },
            "sale_price_text": "$5.42"
        },
        {
            "name": "Samolepka | Nice Shot",
            "hash_name": "Sticker | Nice Shot",
            "sell_listings": 40,
            "sell_price": 230,
            "sell_price_text": "$2.30",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370202198",
                "instanceid": "7454668340",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsj641rifg75kYKuqSNf66b5Pvc9cKKVWjHElLch6LY8Gn_gw0si5WuDmN6vJ3_BOlR1CowwG7Av-d9Y7g",
                "tradable": 1,
                "name": "Samolepka | Nice Shot",
                "name_color": "D2D2D2",
                "type": "Samolepka (Vyšší třída)",
                "market_name": "Samolepka | Nice Shot",
                "market_hash_name": "Sticker | Nice Shot",
                "commodity": 1
            },
            "sale_price_text": "$2.20"
        },
        {
            "name": "Samolepka | Let's Roll-oll (holografická)",
            "hash_name": "Sticker | Let's Roll-oll (Holo)",
            "sell_listings": 38,
            "sell_price": 163,
            "sell_price_text": "$1.63",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370201843",
                "instanceid": "188530139",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsj47030fg_-kprf8i5X0PqhZKsjeKmXXjDGmLcj4OcwH32ywkR04m7TytuoIHvBO1d1CccjQ7INtBO_k8qnab1UOa6C3g",
                "tradable": 1,
                "name": "Samolepka | Let's Roll-oll (holografická)",
                "name_color": "D2D2D2",
                "type": "Samolepka (Významná)",
                "market_name": "Samolepka | Let's Roll-oll (holografická)",
                "market_hash_name": "Sticker | Let's Roll-oll (Holo)",
                "commodity": 1
            },
            "sale_price_text": "$1.56"
        },
        {
            "name": "Samolepka | Have Fun",
            "hash_name": "Sticker | Have Fun",
            "sell_listings": 37,
            "sell_price": 55,
            "sell_price_text": "$0.55",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370192820",
                "instanceid": "7454668340",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsj860_iRwj_0JWy-HoJ6fH2a_0_ePaXDGPFxLsktec9FnrlkUkm6jvcyYqpdXuVOg8-Sswnnu8cDqY",
                "tradable": 1,
                "name": "Samolepka | Have Fun",
                "name_color": "D2D2D2",
                "type": "Samolepka (Vyšší třída)",
                "market_name": "Samolepka | Have Fun",
                "market_hash_name": "Sticker | Have Fun",
                "commodity": 1
            },
            "sale_price_text": "$0.53"
        },
        {
            "name": "Samolepka | Bosh (holografická)",
            "hash_name": "Sticker | Bosh (Holo)",
            "sell_listings": 22,
            "sell_price": 464,
            "sell_price_text": "$4.64",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370198923",
                "instanceid": "188530139",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsj25UrvfhX-kpmuqiQL7aSqO_I6JabFDTaUlrwlseI-G3uwxUUhtWvTzIz8d3mWbFd1C4wwG7C3RapAzQ",
                "tradable": 1,
                "name": "Samolepka | Bosh (holografická)",
                "name_color": "D2D2D2",
                "type": "Samolepka (Významná)",
                "market_name": "Samolepka | Bosh (holografická)",
                "market_hash_name": "Sticker | Bosh (Holo)",
                "commodity": 1
            },
            "sale_price_text": "$4.44"
        },
        {
            "name": "Samolepka | Stupid Banana (speciální)",
            "hash_name": "Sticker | Stupid Banana (Foil)",
            "sell_listings": 21,
            "sell_price": 4444,
            "sell_price_text": "$44.44",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370202138",
                "instanceid": "7454668340",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsjn_kz3SBnOnJfu_Cxa0PShYagjJPSXXTbJwL0utLltGnq3whwi5G-Azt-oIH2RO1VyDZRxRbNf4Rjrlcqnab352TE6HQ",
                "tradable": 1,
                "name": "Samolepka | Stupid Banana (speciální)",
                "name_color": "D2D2D2",
                "type": "Samolepka (Exotická)",
                "market_name": "Samolepka | Stupid Banana (speciální)",
                "market_hash_name": "Sticker | Stupid Banana (Foil)",
                "commodity": 1
            },
            "sale_price_text": "$42.51"
        },
        {
            "name": "Samolepka | Crown (speciální)",
            "hash_name": "Sticker | Crown (Foil)",
            "sell_listings": 15,
            "sell_price": 59725,
            "sell_price_text": "$597.25",
            "app_icon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
            "app_name": "Counter-Strike 2",
            "asset_description": {
                "appid": 730,
                "classid": "370205988",
                "instanceid": "7454668340",
                "background_color": "",
                "icon_url": "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNm1PHic4ERmpsj3-FbwTyL3kZ_ssycDt6v4PvU_dvTGDWGWl-xwtLZoS36ykB4ltTvXy42seS_EPFQpC8BuBbldJQkRI1c",
                "tradable": 1,
                "name": "Samolepka | Crown (speciální)",
                "name_color": "D2D2D2",
                "type": "Samolepka (Exotická)",
                "market_name": "Samolepka | Crown (speciální)",
                "market_hash_name": "Sticker | Crown (Foil)",
                "commodity": 1
            },
            "sale_price_text": "$571.29"
        }
    ]
}