# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Docker build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - run: cd ~/materialy
    - run: whoami
    - run: ls -la
    - run: git pull
    - run: sudo docker compose build
    - run: sudo docker compose up --detach
